import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home, { CardDetails }  from "./components/landingPage";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import { Populor } from "./components/landingPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Home/>
        <Populor/>
        <CardDetails/>
        <Footer/>

        </body>
    </html>
  );
}
